### ISSUE TITLE
5-db-create-reviews-table

### ISSUE THREAD

**Issue by markangelodabu** [2110-FTB-PT/infinite-loop#7]
Story: as a developer, we want to access all reviews that are stored in a reviews table.

Implementation: 
- [x] create table for reviews
- [x] edit columns data (remove itemId / add rating)
- [x] add productId column

**Comment by lindsaynaki** [comment]
@yeonjupark95  do we maybe want to update the ratings data type from int to decimal? for example, if someone rates a product 4.5 or something? and then when we do an overall rating, wouldn't it be an average of all reviews? just a thought!

**Comment by yeonjupark95** [comment]
> @yeonjupark95 do we maybe want to update the ratings data type from int to decimal? for example, if someone rates a product 4.5 or something? and then when we do an overall rating, wouldn't it be an average of all reviews? just a thought!

I thought about it too, i think it's a good call! I'll reopen the ticket and change it tonight.

**Comment by yeonjupark95** [comment]
Change reviews from Integer to decimal
